name: ML CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run model tests
      run: |
        python test.py
        # Check parameter count
        python -c "from model import MNISTModel; model = MNISTModel(); total_params = sum(p.numel() for p in model.parameters()); assert total_params < 25000, f'Model has {total_params} parameters, exceeding 25000 limit'"
    
    - name: Train and validate model
      run: |
        python train.py
        # Check training accuracy from train.log
        python -c "import re; with open('train.log', 'r') as f: log = f.read(); accuracy = float(re.search(r'Final Training Accuracy: ([\d.]+)%', log).group(1)); assert accuracy > 95, f'Training accuracy {accuracy}% is below required 95%'"
    
    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: mnist_model_*.pth